### ISSUE TITLE
关于linear_1，2两个全连接层的疑问？

### ISSUE THREAD

**Issue by xhw205** [powerycy/Efficient-GlobalPointer#1]
`    self.linear_1 = nn.Linear(hidden_size,hidden_size * 2,bias=True)
        self.linear_2 = nn.Linear(hidden_size * 2,heads * 2,bias=True)`

这似乎与苏神的不一样吧？苏神的是
`        self.dense_1 = Dense(
            units=self.head_size * 2,
            use_bias=self.use_bias,
            kernel_initializer=self.kernel_initializer
        )
        self.dense_2 = Dense(
            units=self.heads * 2,
            use_bias=self.use_bias,
            kernel_initializer=self.kernel_initializer
        )`
       第一个全连接层您的输出是`hidden_size * 2`,苏神的是`head_size * 2`

**Comment by powerycy** [comment]
感谢，这点确实写错了。。
